name: cookiecutter-mdakit-docs
channels:
  - conda-forge
dependencies:
  # Base depends
  - python
  - pip

  - mdanalysis-sphinx-theme >=1.0.1
  - tree

  # Pip-only installs
  - pip:
    - pyyaml
    - cookiecutter
    - sphinxcontrib-versioning


