name: cookiecutter-mdakit-docs
channels:
  - conda-forge
dependencies:
  # Base depends
  - python
  - pip

  - sphinx<7.0
  - sphinx_rtd_theme

  - tree

  # Pip-only installs
  - pip:
    - pyyaml
    - cookiecutter
    - sphinxcontrib-versioning


