name: Cookiecutter CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # weekly tests
    - cron: "0 0 * * 0"

# Custom global env block (Has to be recreated in each matrix, can't pass sequences to this)
env:  # I want to share these between jobs, but I can't access the env from inside matrix, has to be on the steps.
  licenses: "1 2"
  depend-sources: "1 2 3"
  rtd: "1 2"

defaults:
  run:
    shell: bash

jobs:
  generate-cookiecutter:
    name: "Cookiecutter Artifacts"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
        dependency_source: [1, 2, 3]
        rtd: [1, 2]
    env:
      TEST_REPO_NAME: "testmdakit_deps-${{ matrix.dependency_source }}_rtd-${{ matrix.rtd }}"


    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U cookiecutter

      - name: Construct cookiecutter
        shell: bash
        run: |
          cookiecutter --verbose --output-dir $TEST_REPO_NAME --no-input . \
            --project_name $TEST_REPO_NAME \
            --repo-name cookiecutter-mda \
            --github_username github-actions-ci \
            --github_host_account MDAnalysis \
            --author_name "Github Actions CI" \
            --author_email "github-action@users.noreply.github.com" \
            --description "Test MDAKit repository: deps=${{ matrix.dependency_source }}, rtd=${{ matrix.rtd }}" \
            --dependency_source ${{ matrix.dependency_source }} \
            --include_ReadTheDocs ${{ matrix.rtd }}
        
      - name: 


  compare-action-output:
    name: "Compare GHA Output"
    runs-on: ubuntu-latest
    needs: "generate-cookiecutter"
    strategy:
      matrix:
        license: [1, 2]
        depend-source: [1, 2, 3]
        rtd: [1, 2]

    steps:
      - uses: actions/checkout@v1

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

      - name: "Compare Reference CI"
        shell: bash
        run: |
          COMBO="${{ matrix.license }}_${{ matrix.depend-source }}_${{ matrix.rtd }}"
          mv prj_$COMBO/.github/workflows/CI.yaml CI_$COMBO.yaml
          COMPARE=$(diff CI_$COMBO.yaml .github/reference-workflows/CI_$COMBO.yaml)
          if [[ ! -z $COMPARE ]]
          then
              echo "CI_$COMBO.yaml differs from reference!"
              echo $COMPARE
              exit 1
          fi


  conda-forge-dep:
    needs: "generate-cookiecutter"
    name: Test CF (Approx) on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:  # Approximate strategy, uses a few other options
      matrix:
        os: [ubuntu-latest , macOS-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
        license: [1]  # Nonstandard
        rtd: [1, 2]  # Nonstandard
    steps:
      # - uses: actions/checkout@v1  # This isn't necessary here

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

#      - name: "Change directory"  # Have to CD here to make sure this works
#        shell: bash
#        run: |
      #          cd prj_${{ matrix.license }}_1_${{ matrix.rtd }}

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: prj_${{ matrix.license }}_1_${{ matrix.rtd }}/devtools/conda-envs/test_env.yaml

          channels: conda-forge,defaults

          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package

        # conda setup requires this special shell
        shell: bash -l {0}
        working-directory: prj_${{ matrix.license }}_1_${{ matrix.rtd }}  # Nonstandard
        run: |
          python -m pip install . --no-deps
          conda list


      - name: Run tests

        # conda setup requires this special shell
        shell: bash -l {0}
        working-directory: prj_${{ matrix.license }}_1_${{ matrix.rtd }}  # Nonstandard
        run: |
          pytest -v --cov=prj_${{ matrix.license }}_1_${{ matrix.rtd }} --cov-report=xml --color=yes prj_${{ matrix.license }}_1_${{ matrix.rtd }}/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./prj_${{ matrix.license }}_1_${{ matrix.rtd }}/coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}


  conda-defaults-dep:
    needs: "generate-cookiecutter"
    name: Test Conda Defaults (Approx) on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:  # Approximate strategy, uses a few other options
      matrix:
        os: [ubuntu-latest , macOS-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
        license: [1]  # Nonstandard
        rtd: [1, 2]  # Nonstandard

    steps:
      # - uses: actions/checkout@v1  # This isn't necessary here

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs

#      - name: "Change directory"  # Have to CD here to make sure this works
#        shell: bash
#        run: |
      #          cd prj_${{ matrix.license }}_2_${{ matrix.rtd }}

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: prj_${{ matrix.license }}_2_${{ matrix.rtd }}/devtools/conda-envs/test_env.yaml

          activate-environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package

        # conda setup requires this special shell
        shell: bash -l {0}
        working-directory: prj_${{ matrix.license }}_2_${{ matrix.rtd }}  # Nonstandard
        run: |
          python -m pip install . --no-deps
          conda list


      - name: Run tests

        # conda setup requires this special shell
        shell: bash -l {0}
        working-directory: prj_${{ matrix.license }}_2_${{ matrix.rtd }}  # Nonstandard
        run: |
          pytest -v --cov=prj_${{ matrix.license }}_2_${{ matrix.rtd }} --cov-report=xml --color=yes prj_${{ matrix.license }}_2_${{ matrix.rtd }}/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./prj_${{ matrix.license }}_2_${{ matrix.rtd }}/coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

  pip-dep:
    needs: "generate-cookiecutter"
    name: Test Pip (Approx) on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:  # Approximate strategy, uses a few other options
      matrix:
        os: [ubuntu-latest , macOS-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
        license: [1]  # Nonstandard
        rtd: [1, 2]  # Nonstandard

    steps:
      # - uses: actions/checkout@v1  # This isn't necessary here

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: "Fetch Artifacts"
        uses: actions/download-artifact@v2
        with:
          name: cookiecutter_outputs


#      - name: "Change directory"  # Have to CD here to make sure this works
#        shell: bash
#        run: |
      #          cd prj_${{ matrix.license }}_3_${{ matrix.rtd }}


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Testing Dependencies
        shell: bash
        run: |
          python -m pip install -U pytest pytest-cov codecov

      - name: Install package

        shell: bash
        working-directory: prj_${{ matrix.license }}_3_${{ matrix.rtd }}  # Nonstandard
        run: |
          python -m pip install .


      - name: Run tests

        shell: bash
        working-directory: prj_${{ matrix.license }}_3_${{ matrix.rtd }} # Nonstandard
        run: |
          pytest -v --cov=prj_${{ matrix.license }}_3_${{ matrix.rtd }} --cov-report=xml --color=yes prj_${{ matrix.license }}_3_${{ matrix.rtd }}/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./prj_${{ matrix.license }}_3_${{ matrix.rtd }}/coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}