name: {{cookiecutter.repo_name}}-docs
channels:
dependencies:
    # Base depends
  - python
  - pip

  - sphinx
{% if cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback' %}
  # Pip-only installs
  - pip:
    - sphinx_rtd_theme
{% else %}
  - sphinx_rtd_theme

    # Pip-only installs
  #- pip:
{% endif %}
