name: {{cookiecutter.repo_name}}-docs
channels:
{% if cookiecutter.dependency_source == 'Prefer default anaconda channel with pip fallback' %}
  - defaults
{% else %}
  - conda-forge
{% endif %}
dependencies:
    # Base depends
  - python
  - pip

  - mdanalysis-sphinx-theme >=1.0.1
    # Pip-only installs
  #- pip:
